/**
 * SEO Agent for osama-me.digital
 *
 * Autonomous agent that scans the Next.js codebase for SEO issues
 * and directly edits the source files to fix them.
 *
 * Runs daily via GitHub Actions.
 * Requires: ANTHROPIC_API_KEY environment variable
 */

import { query } from "@anthropic-ai/claude-agent-sdk";

const SITE_URL = "https://osama-me.digital";
const PROJECT_ROOT = process.env.GITHUB_WORKSPACE ?? process.cwd().replace("/seo-agent", "");

const SEO_AGENT_PROMPT = `
You are an expert SEO engineer and Next.js developer. Your job is to audit and fix the website at ${SITE_URL} by directly editing the source code in ${PROJECT_ROOT}.

This is a Next.js 16 (App Router) TypeScript website for Osama Tahir — a Web Developer & Digital Marketing Specialist based in Dubai, UAE.

## YOUR MISSION
Perform a full SEO audit and FIX every issue you find. Do not just report — actually edit the files.

## AUDIT & FIX CHECKLIST

### 1. META TAGS (src/app/**/page.tsx, src/app/layout.tsx)
- Every page must have a unique <title> (50-60 chars) with primary keyword + "Dubai"
- Every page must have a unique <meta description> (140-160 chars) that is compelling
- Check generateMetadata() exports on every page
- Fix missing, duplicate, or weak titles/descriptions

### 2. OPEN GRAPH & TWITTER CARDS (src/app/**/page.tsx)
- Every page needs og:title, og:description, og:image, og:url
- og:image should point to /og-image.png (already exists in public/)
- Twitter card type should be "summary_large_image"
- Fix any missing OG/Twitter meta

### 3. SCHEMA MARKUP (src/lib/schema.ts or wherever it lives)
- Homepage: Person schema + LocalBusiness schema
- Services pages: Service schema
- Blog posts: BlogPosting schema with datePublished, dateModified, author
- Check all schema is valid JSON-LD and complete
- Add missing schema where needed

### 4. HEADING STRUCTURE (src/app/**/page.tsx, src/components/**)
- One H1 per page, must contain primary keyword
- H2s for major sections, H3s for subsections
- No skipped heading levels (e.g. H1 → H3)
- Fix heading hierarchy issues

### 5. IMAGES (src/components/**/*, src/app/**/*.tsx)
- Every <img> tag must become Next.js <Image> component
- Every image must have descriptive alt text (not empty, not "image")
- Alt text should include keywords naturally
- Fix missing or poor alt text

### 6. INTERNAL LINKING (src/components/**/*, src/app/**/*.tsx)
- Services should link to related blog posts and vice versa
- Add relevant anchor text (not "click here" or "read more")
- Ensure all service pages are linked from homepage
- Add breadcrumb navigation where missing

### 7. SITEMAP (src/app/sitemap.ts)
- All pages must be in sitemap
- Priority: homepage=1.0, services=0.9, blog=0.8, other=0.7
- lastModified should be current date
- changeFrequency: homepage='weekly', blog='daily', services='monthly'
- Fix any missing pages or wrong priorities

### 8. ROBOTS.TXT (src/app/robots.ts)
- Allow all legitimate crawlers
- Allow: GPTBot, ClaudeBot, PerplexityBot, Googlebot, Bingbot
- Disallow: /api/, /_next/
- Sitemap URL must be correct absolute URL
- Fix any issues

### 9. LLMS.TXT (src/app/llms.txt or public/llms.txt)
- Check if llms.txt exists and is well-structured
- Should describe Osama's expertise, services, location
- Should be AI-readable and useful for AI search engines
- Create or improve it

### 10. PERFORMANCE (next.config.ts)
- Images should use next/image with proper sizes
- Fonts should use next/font
- Check for any obvious performance config issues

### 11. CONTENT QUALITY (src/data/**, src/app/**/page.tsx)
- Check blog posts for thin content (less than 300 words is a problem)
- Services pages should have clear value propositions
- Add FAQ sections where they would help SEO
- Check for keyword stuffing or missing keywords

### 12. LOCAL SEO
- Every services page should mention "Dubai" and "UAE"
- Google Business Profile markup
- NAP consistency (Name, Address, Phone)

## HOW TO WORK
1. First, use Glob to discover all .tsx, .ts files in src/
2. Read each page file to audit its SEO
3. Read components to check images and headings
4. Edit files to fix every issue you find
5. After editing, verify your changes make sense
6. Run: cd ${PROJECT_ROOT} && npx tsc --noEmit 2>&1 | head -50 to check for TypeScript errors
7. Fix any TypeScript errors you introduced

## IMPORTANT RULES
- Make real edits — do not just describe what to do
- Keep the existing code style and formatting
- Do not break existing functionality
- Test that imports are correct after editing
- Commit message will be auto-generated by GitHub Actions

Start the audit now. Work through every file systematically.
`;

async function runSeoAgent() {
  console.log("🚀 SEO Agent starting...");
  console.log(`📁 Project root: ${PROJECT_ROOT}`);
  console.log(`🌐 Site: ${SITE_URL}`);
  console.log(`⏰ Run time: ${new Date().toISOString()}`);
  console.log("─".repeat(60));

  let totalMessages = 0;
  let fixesApplied = 0;

  try {
    for await (const message of query({
      prompt: SEO_AGENT_PROMPT,
      options: {
        cwd: PROJECT_ROOT,
        allowedTools: [
          "Read",
          "Write",
          "Edit",
          "Bash",
          "Glob",
          "Grep",
          "WebFetch",
        ],
        permissionMode: "acceptEdits",
        maxTurns: 100,
        model: "claude-opus-4-6",
      },
    })) {
      totalMessages++;

      if ("result" in message) {
        console.log("\n" + "═".repeat(60));
        console.log("✅ SEO AGENT COMPLETED");
        console.log("═".repeat(60));
        console.log(message.result);
        console.log(`\n📊 Total agent turns: ${totalMessages}`);
      } else if (message.type === "assistant") {
        // Print agent thinking/actions
        if (Array.isArray(message.message?.content)) {
          for (const block of message.message.content) {
            if (block.type === "text" && block.text) {
              process.stdout.write(block.text);
              // Count fixes
              if (
                block.text.includes("Fixed") ||
                block.text.includes("Updated") ||
                block.text.includes("Added")
              ) {
                fixesApplied++;
              }
            } else if (block.type === "tool_use") {
              if (block.name === "Edit" || block.name === "Write") {
                const filePath = (block.input as Record<string, string>)
                  ?.file_path;
                console.log(`\n🔧 Editing: ${filePath}`);
                fixesApplied++;
              } else if (block.name === "Bash") {
                console.log(`\n⚡ Running: ${(block.input as Record<string, string>)?.command?.slice(0, 80)}...`);
              }
            }
          }
        }
      }
    }

    console.log(`\n✨ Fixes applied: ${fixesApplied}`);
    console.log("🏁 Agent run complete.");
    process.exit(0);
  } catch (error) {
    console.error("\n❌ SEO Agent failed:", error);
    process.exit(1);
  }
}

runSeoAgent();
